"""Canonical planner baseline roster (people, teams, managers, tags).

Used by ``seed_planner`` when the database is empty. Kept in Python so the
HTML app does not ship a second copy of the employee list.
"""

from __future__ import annotations

from typing import Any


def baseline_state() -> dict[str, Any]:
    return {
        "people": [
            {
                "id": "jvo",
                "name": "Jonas Vo",
                "email": "jvo@blackcapitaltechnology.com",
                "org": "BCT",
            },
            {
                "id": "skj",
                "name": "Stefan Konrad Johansen",
                "mbti": "ESTJ-A",
                "title": "Managing Director",
                "org": "BCG",
                "fn": "Management",
                "loc": "Oslo Norway",
                "email": "skj@blackcapitalventures.com",
                "phone": "(+45) 60 92 80 03",
                "linkedin": "linkedin.com/in/k-bak/",
                "dessert": "Ice cream",
                "projects": [],
            },
            {
                "id": "mr",
                "name": "Malthe Reipurth",
                "mbti": "ENTJ-A",
                "title": "Managing Director",
                "org": "BCT",
                "fn": "Management",
                "loc": "Aalborg Denmark",
                "email": "mr@blackcapitalventures.com",
                "phone": "(+45) 52 25 50 55",
                "linkedin": "linkedin.com/in/57192/",
                "dessert": "Créme Brûlée og portvin fra Aarstová Torshavn",
                "projects": [],
            },
            {
                "id": "tor",
                "name": "Tor Duerlund Emanuelssen",
                "mbti": "",
                "title": "Business Developer",
                "org": "BCT",
                "fn": "Business Development",
                "loc": "Aalborg Denmark",
                "email": "tor@blackcapitaltechnology.com",
                "phone": "",
                "linkedin": "linkedin.com/in/elsen/",
                "dessert": "",
                "projects": [],
            },
            {
                "id": "cdo",
                "name": "Charlie Østergaard",
                "mbti": "ENFJ-A",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "cdo@blackcapitaltechnology.com",
                "phone": "(+45) 52 22 66 13",
                "linkedin": "linkedin.com/in/gaard/",
                "dessert": "Créme Brûlée / Pancakes with ice cream",
                "projects": [],
            },
            {
                "id": "jbr",
                "name": "Jonas Blendstrup Rasmussen",
                "mbti": "INFJ-T",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "jbr@blackcapitaltechnology.com",
                "phone": "",
                "linkedin": "linkedin.com/in/73200/",
                "dessert": "Ice cream",
                "projects": [],
            },
            {
                "id": "jo",
                "name": "Jonas Vestergård Olsen",
                "mbti": "INTP-T",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "jo@blackcapitaltechnology.com",
                "phone": "",
                "linkedin": "linkedin.com/in/jvolsen/",
                "dessert": "",
                "projects": [],
            },
            {
                "id": "jl",
                "name": "Jesper Luff Olesen",
                "mbti": "",
                "title": "Business Developer",
                "org": "BCT",
                "fn": "Business Development",
                "loc": "Aalborg Denmark",
                "email": "jl@blackcapitaltechnology.com",
                "phone": "",
                "linkedin": "linkedin.com/in/rluff/",
                "dessert": "Gammeldags æblekage",
                "projects": [],
            },
            {
                "id": "csv",
                "name": "Christian Skou Vendelbjerg",
                "mbti": "",
                "title": "Studentermedhjælper",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "csv@blackcapitaltechnology.com",
                "phone": "(+45) 31 67 30 77",
                "linkedin": "linkedin.com/in/77339/",
                "dessert": "Brownie",
                "projects": [],
            },
            {
                "id": "ab",
                "name": "Astrid Bak",
                "mbti": "INFJ-T",
                "title": "Marketing assistant",
                "org": "BCT",
                "fn": "Marketing",
                "loc": "Aalborg Denmark",
                "email": "ab@blackcapitaltechnology.com",
                "phone": "(+45) 52 30 25 71",
                "linkedin": "linkedin.com/in/b42b4/",
                "dessert": "Brunsviger",
                "projects": [],
            },
            {
                "id": "czr",
                "name": "Casper Zacho Roskær",
                "mbti": "",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "czr@blackcapitaltechnology.com",
                "phone": "(+45) 61 60 12 22",
                "linkedin": "linkedin.com/in/99222/",
                "dessert": "Flæskesvær",
                "projects": [],
            },
            {
                "id": "lnp",
                "name": "Lars Nyborg Pedersen",
                "mbti": "INTJ-T",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "lnp@blackcapitalventures.com",
                "phone": "(+45) 22 55 55 03",
                "linkedin": "linkedin.com/in/ersen/",
                "dessert": "Chocolate mousse",
                "projects": [],
            },
            {
                "id": "jkm",
                "name": "Julie Krause Madsen",
                "mbti": "",
                "title": "Graphic Designer",
                "org": "BCT",
                "fn": "Marketing",
                "loc": "Aalborg Denmark",
                "email": "jkm@blackcapitaltechnology.com",
                "phone": "(+45) 25 37 20 90",
                "linkedin": "linkedin.com/in/adsen/",
                "dessert": "Bland selv slik (surt vandmelonsslik)",
                "projects": [],
            },
            {
                "id": "mkk",
                "name": "Martin Kenth Knudsen",
                "mbti": "",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "mkk@blackcapitaltechnology.com",
                "phone": "",
                "linkedin": "linkedin.com/in/kenth/",
                "dessert": "",
                "projects": [],
            },
            {
                "id": "rfh",
                "name": "Rasmus Frydenlund Hansen",
                "mbti": "ENFJ-A",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "Rasmusfrydenlund@hotmail.com",
                "phone": "(+45) 28 70 38 62",
                "linkedin": "linkedin.com/in/ansen/",
                "dessert": "Japansk, Buffet",
                "projects": [],
            },
            {
                "id": "dip",
                "name": "Daniel Prior",
                "mbti": "",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "dip@blackcapitaltechnology.com",
                "phone": "(+54) 26 83 40 88",
                "linkedin": "linkedin.com/in/79195/",
                "dessert": "Citronmåne - en god en",
                "projects": [],
            },
            {
                "id": "bej",
                "name": "Benjamin Jensen",
                "mbti": "",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "bej@blackcapitaltechnology.com",
                "phone": "",
                "linkedin": "linkedin.com/in/jamin/",
                "dessert": "",
                "projects": [],
            },
            {
                "id": "tmg",
                "name": "Trond Magnus Gulbrandsen",
                "mbti": "INTJ-A",
                "title": "Business Developer",
                "org": "BCT",
                "fn": "Business Development",
                "loc": "Oslo Norway",
                "email": "tmg@blackcapitaltechnology.com",
                "phone": "(+47) 90 70 08 63",
                "linkedin": "linkedin.com/in/andsen",
                "dessert": "Anything m mørk sjokolade",
                "projects": [],
            },
            {
                "id": "jgk",
                "name": "Jesper Guldhammer Klötzl",
                "mbti": "",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "jgk@blackcapitaltechnology.com",
                "phone": "(+45) 20 82 78 85",
                "linkedin": "linkedin.com/in/b8582/",
                "dessert": "Gateau Marcel",
                "projects": [],
            },
            {
                "id": "ndn",
                "name": "Niklas Due Nim",
                "mbti": "",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "ndn@blackcapital.com",
                "phone": "(+45) 31 77 15 38",
                "linkedin": "",
                "dessert": "Pepsi Max",
                "projects": [],
            },
            {
                "id": "amm",
                "name": "Aleksander Mosekjær Møller",
                "mbti": "",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "amm@blackcapitaltechnology.com",
                "phone": "(+45) 31785513",
                "linkedin": "",
                "dessert": "Nutella",
                "projects": [],
            },
            {
                "id": "trd",
                "name": "Thomas Ranum Damsgaard",
                "mbti": "",
                "title": "Software Developer",
                "org": "BCT",
                "fn": "Engineering",
                "loc": "Aalborg Denmark",
                "email": "trd@blackcapitaltechnology.com",
                "phone": "27850234",
                "linkedin": "linkedin.com/in/03202/",
                "dessert": "Tiramisu",
                "projects": [],
            },
        ],
        "mgrs": ["tor", "mr", "skj"],
        "teams": {
            "team-1": ["cdo", "jbr", "jl", "ab", "lnp", "dip"],
            "team-2": ["jo", "czr", "jkm", "rfh", "bej", "ndn"],
            "team-3": ["csv", "mkk", "tmg", "jgk", "amm", "trd"],
            "pool": [],
        },
        "startDate": "2026-01-05",
        "customDates": {},
        "workHours": {
            "start": "09:00",
            "end": "17:00",
            "excludeLunch": True,
            "weekdaysOnly": True,
        },
        "viewedMgrFilter": "all",
        "weekOffset": 0,
        "weeksPerSession": 2,
        "projects": [],
        "journal": {},
        "fnTags": [
            {"label": "ENG", "displayName": "Engineering", "color": "#6ea8fe"},
            {"label": "BD", "displayName": "Business Development", "color": "#f5a97f"},
            {"label": "MKT", "displayName": "Marketing", "color": "#a6da95"},
            {"label": "MGMT", "displayName": "Management", "color": "#c6a0f6"},
        ],
    }
