# Generated by Django 5.2.17 on 2026-08-10 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_assignment_assigned_by_welcome_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingassignment",
            name="buddy_email",
            field=models.EmailField(
                blank=True,
                help_text="Optional — entered by the manager when attaching the flow. Available in the welcome email as the {{ buddy_email }} merge tag.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="onboardingassignment",
            name="buddy_name",
            field=models.CharField(
                blank=True,
                help_text="Optional — entered by the manager when attaching the flow. Available in the welcome email as the {{ buddy_name }} merge tag.",
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="WelcomeEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                ("html_body", models.TextField()),
                (
                    "is_default_fallback",
                    models.BooleanField(
                        default=False,
                        help_text="Used for any flow that doesn't have its own welcome email template yet. Only one template in the system can be the fallback.",
                    ),
                ),
                (
                    "flow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welcome_email_template",
                        to="onboarding.onboardingflow",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
