# Generated by Django 5.2.17 on 2026-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_onboardingassignment_buddy_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingassignment',
            name='leder_email',
            field=models.EmailField(blank=True, help_text="Snapshot of the employee's planner Person.leder email at attach/schedule time. See leder_name.", max_length=254),
        ),
        migrations.AddField(
            model_name='onboardingassignment',
            name='leder_name',
            field=models.CharField(blank=True, help_text="Snapshot of the employee's planner Person.leder ('leder' — the manager they report to) name at attach/schedule time. Available in the welcome email as the {{ leder_name }} merge tag, and as the default meeting organizer for calendar_meeting steps (role 'leder', which is also what an unspecified role falls back to).", max_length=128),
        ),
        migrations.AddField(
            model_name='onboardingassignment',
            name='scheduled_automation_ran_at',
            field=models.DateTimeField(blank=True, help_text="Set once the attach automation (welcome email, calendar booking, Slack invite) has been attempted for this assignment — immediately at attach time, or later by run_scheduled_onboarding once scheduled_for arrives. Never re-attempted after this is set, mirroring welcome_email_sent_at's 'only ever once' semantics.", null=True),
        ),
        migrations.AddField(
            model_name='onboardingassignment',
            name='scheduled_for',
            field=models.DateField(blank=True, help_text="The date this onboarding flow is planned to kick off. When this is today or in the past at attach time, the welcome email / calendar booking / Slack invite automation runs immediately. When it's in the future, the automation is deferred until that date (see management command run_scheduled_onboarding and scheduled_automation_ran_at).", null=True),
        ),
        migrations.AlterField(
            model_name='onboardingassignment',
            name='buddy_email',
            field=models.EmailField(blank=True, help_text="Snapshot of the employee's planner Person.buddy email at attach/schedule time. See buddy_name.", max_length=254),
        ),
        migrations.AlterField(
            model_name='onboardingassignment',
            name='buddy_name',
            field=models.CharField(blank=True, help_text="Snapshot of the employee's planner Person.buddy name at attach/schedule time. Locked in alongside the welcome email, which only ever sends once. Available in the welcome email as the {{ buddy_name }} merge tag, and as the default meeting organizer for calendar_meeting steps configured with role 'buddy'.", max_length=128),
        ),
    ]
