# Generated by Django 5.2.17 on 2026-10-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_employee_documents_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsettings',
            name='system_email',
            field=models.EmailField(blank=True, help_text='System account used for meetings, welcome emails and Drive uploads. Empty = none; unset = ONBOARDING_SCHEDULER_EMAIL.', max_length=254, null=True),
        ),
    ]
