# Generated by Django 5.2.14 on 2026-05-11 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_start', models.DateField()),
                ('session_index', models.PositiveSmallIntegerField()),
                ('team', models.CharField(choices=[('team-1', 'Team 1'), ('team-2', 'Team 2'), ('team-3', 'Team 3'), ('pool', 'Pool')], max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_sessions', to='planner.managerprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cycle_start', 'session_index', 'team'],
                'unique_together': {('cycle_start', 'session_index', 'team')},
            },
        ),
        migrations.CreateModel(
            name='CheckInMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('title', models.CharField(blank=True, default='Check-in samtale', max_length=255)),
                ('agenda', models.TextField(blank=True, default='')),
                ('google_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('google_html_link', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in', to='planner.journalentry')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to='planner.managerprofile')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to='planner.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='planner.rotationsession')),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['manager', 'starts_at'], name='planner_che_manager_51e561_idx'), models.Index(fields=['person', 'starts_at'], name='planner_che_person__1d456e_idx'), models.Index(fields=['status'], name='planner_che_status_ffb664_idx')],
            },
        ),
    ]
