# Generated by Django 5.2.17 on 2026-08-11 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0010_checkinmeeting_google_meet_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="checkinmeeting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("manager", "person", "session"),
                name="uniq_active_checkin_per_manager_person_session",
            ),
        ),
    ]
