# Generated by Django 5.2.17 on 2026-08-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_checkinmeeting_unique_active_per_session'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarsharerequest',
            new_name='planner_cal_person__f52fc5_idx',
            old_name='planner_cal_person__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='managernotification',
            new_name='planner_man_manager_5fb70d_idx',
            old_name='planner_mgr_notif_read_idx',
        ),
        migrations.AddField(
            model_name='person',
            name='buddy',
            field=models.ForeignKey(blank=True, help_text='The onboarding buddy assigned to guide/help this person. Selectable anywhere a Person is edited; required to attach/schedule an onboarding flow for this person (see apps.onboarding).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddy_for', to='planner.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='leder',
            field=models.ForeignKey(blank=True, help_text="The manager ('leder') this person reports to. Selectable anywhere a Person is edited; required to attach/schedule an onboarding flow for this person (see apps.onboarding).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='planner.person'),
        ),
    ]
